apiVersion: v1
kind: Secret
metadata:
  name: my-app-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/YuqingWang2020/my-app-manifests
  type: git